<?php
declare(strict_types=1);

use Kkkonrad\Gdpr\Block\Consent\FormConfig;
use Magento\Framework\Escaper;

/** @var FormConfig $block */
/** @var Escaper $escaper */
?>
<div data-kkkonrad-gdpr-form-consents
     data-frontend-adapter="<?= $escaper->escapeHtmlAttr((string)($block->getData('frontend_adapter') ?: 'luma')) ?>"
     data-config="<?= $escaper->escapeHtmlAttr($block->getJsonConfig()) ?>"
     hidden></div>
